# Generated by Django 5.1.4 on 2025-02-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientManagement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="Электронная почта")),
                ("full_name", models.CharField(max_length=150, verbose_name="Ф. И. О.")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=200, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Содержание письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_sending",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки первого письма"),
                ),
                ("end_sending", models.DateTimeField(auto_now=True, verbose_name="Дата окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Completed", "Завершена"), ("Created", "Создана"), ("Launched", "Запущена")],
                        default="Created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("addressees", models.ManyToManyField(to="mailsender.clientmanagement")),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailsender.message")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "успешно"), ("failed", "не успешно")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("server_answer", models.TextField(verbose_name="Ответ почтового сервера")),
                ("mailing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailsender.mailing")),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
